/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedOrganizationsOrgIdRouteRouteImport } from './routes/_authenticated/organizations/$orgId/route'
import { Route as AuthenticatedOrganizationsOrgIdWorkspacesIndexRouteImport } from './routes/_authenticated/organizations/$orgId/workspaces.index'
import { Route as AuthenticatedOrganizationsOrgIdGatewaysIndexRouteImport } from './routes/_authenticated/organizations/$orgId/gateways.index'
import { Route as AuthenticatedOrganizationsOrgIdDefinitionsIndexRouteImport } from './routes/_authenticated/organizations/$orgId/definitions.index'
import { Route as AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteImport } from './routes/_authenticated/organizations/$orgId/workspaces/$workspaceId/route'
import { Route as AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteImport } from './routes/_authenticated/organizations/$orgId/gateways/$gatewayId/route'
import { Route as AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteImport } from './routes/_authenticated/organizations/$orgId/definitions/$definitionId/route'
import { Route as AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRouteImport } from './routes/_authenticated/organizations/$orgId/workspaces/$workspaceId/end-devices'
import { Route as AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRouteImport } from './routes/_authenticated/organizations/$orgId/gateways/$gatewayId/overview'
import { Route as AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRouteImport } from './routes/_authenticated/organizations/$orgId/definitions/$definitionId/overview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRouteRoute =
  AuthenticatedOrganizationsOrgIdRouteRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute =
  AuthenticatedOrganizationsOrgIdWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdGatewaysIndexRoute =
  AuthenticatedOrganizationsOrgIdGatewaysIndexRouteImport.update({
    id: '/gateways/',
    path: '/gateways/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute =
  AuthenticatedOrganizationsOrgIdDefinitionsIndexRouteImport.update({
    id: '/definitions/',
    path: '/definitions/',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute =
  AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute =
  AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteImport.update({
    id: '/gateways/$gatewayId',
    path: '/gateways/$gatewayId',
    getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute =
  AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteImport.update(
    {
      id: '/definitions/$definitionId',
      path: '/definitions/$definitionId',
      getParentRoute: () => AuthenticatedOrganizationsOrgIdRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute =
  AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRouteImport.update(
    {
      id: '/end-devices',
      path: '/end-devices',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute,
    } as any,
  )
const AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute =
  AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () =>
      AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute =
  AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRouteImport.update(
    {
      id: '/overview',
      path: '/overview',
      getParentRoute: () =>
        AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteRouteWithChildren
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/organizations/$orgId/definitions/$definitionId': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren
  '/organizations/$orgId/gateways/$gatewayId': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren
  '/organizations/$orgId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/organizations/$orgId/definitions': typeof AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute
  '/organizations/$orgId/gateways': typeof AuthenticatedOrganizationsOrgIdGatewaysIndexRoute
  '/organizations/$orgId/workspaces': typeof AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute
  '/organizations/$orgId/definitions/$definitionId/overview': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute
  '/organizations/$orgId/gateways/$gatewayId/overview': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute
  '/organizations/$orgId/workspaces/$workspaceId/end-devices': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteRouteWithChildren
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/organizations/$orgId/definitions/$definitionId': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren
  '/organizations/$orgId/gateways/$gatewayId': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren
  '/organizations/$orgId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/organizations/$orgId/definitions': typeof AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute
  '/organizations/$orgId/gateways': typeof AuthenticatedOrganizationsOrgIdGatewaysIndexRoute
  '/organizations/$orgId/workspaces': typeof AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute
  '/organizations/$orgId/definitions/$definitionId/overview': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute
  '/organizations/$orgId/gateways/$gatewayId/overview': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute
  '/organizations/$orgId/workspaces/$workspaceId/end-devices': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRouteRouteWithChildren
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/organizations/$orgId/definitions/$definitionId': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren
  '/_authenticated/organizations/$orgId/gateways/$gatewayId': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren
  '/_authenticated/organizations/$orgId/workspaces/$workspaceId': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_authenticated/organizations/$orgId/definitions/': typeof AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute
  '/_authenticated/organizations/$orgId/gateways/': typeof AuthenticatedOrganizationsOrgIdGatewaysIndexRoute
  '/_authenticated/organizations/$orgId/workspaces/': typeof AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute
  '/_authenticated/organizations/$orgId/definitions/$definitionId/overview': typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute
  '/_authenticated/organizations/$orgId/gateways/$gatewayId/overview': typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute
  '/_authenticated/organizations/$orgId/workspaces/$workspaceId/end-devices': typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/organizations'
    | '/'
    | '/organizations/$orgId'
    | '/organizations/'
    | '/organizations/$orgId/definitions/$definitionId'
    | '/organizations/$orgId/gateways/$gatewayId'
    | '/organizations/$orgId/workspaces/$workspaceId'
    | '/organizations/$orgId/definitions'
    | '/organizations/$orgId/gateways'
    | '/organizations/$orgId/workspaces'
    | '/organizations/$orgId/definitions/$definitionId/overview'
    | '/organizations/$orgId/gateways/$gatewayId/overview'
    | '/organizations/$orgId/workspaces/$workspaceId/end-devices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/organizations/$orgId'
    | '/organizations'
    | '/organizations/$orgId/definitions/$definitionId'
    | '/organizations/$orgId/gateways/$gatewayId'
    | '/organizations/$orgId/workspaces/$workspaceId'
    | '/organizations/$orgId/definitions'
    | '/organizations/$orgId/gateways'
    | '/organizations/$orgId/workspaces'
    | '/organizations/$orgId/definitions/$definitionId/overview'
    | '/organizations/$orgId/gateways/$gatewayId/overview'
    | '/organizations/$orgId/workspaces/$workspaceId/end-devices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/organizations'
    | '/_authenticated/'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/organizations/'
    | '/_authenticated/organizations/$orgId/definitions/$definitionId'
    | '/_authenticated/organizations/$orgId/gateways/$gatewayId'
    | '/_authenticated/organizations/$orgId/workspaces/$workspaceId'
    | '/_authenticated/organizations/$orgId/definitions/'
    | '/_authenticated/organizations/$orgId/gateways/'
    | '/_authenticated/organizations/$orgId/workspaces/'
    | '/_authenticated/organizations/$orgId/definitions/$definitionId/overview'
    | '/_authenticated/organizations/$orgId/gateways/$gatewayId/overview'
    | '/_authenticated/organizations/$orgId/workspaces/$workspaceId/end-devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/organizations/$orgId/workspaces/': {
      id: '/_authenticated/organizations/$orgId/workspaces/'
      path: '/workspaces'
      fullPath: '/organizations/$orgId/workspaces'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/gateways/': {
      id: '/_authenticated/organizations/$orgId/gateways/'
      path: '/gateways'
      fullPath: '/organizations/$orgId/gateways'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/definitions/': {
      id: '/_authenticated/organizations/$orgId/definitions/'
      path: '/definitions'
      fullPath: '/organizations/$orgId/definitions'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/workspaces/$workspaceId': {
      id: '/_authenticated/organizations/$orgId/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/organizations/$orgId/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/gateways/$gatewayId': {
      id: '/_authenticated/organizations/$orgId/gateways/$gatewayId'
      path: '/gateways/$gatewayId'
      fullPath: '/organizations/$orgId/gateways/$gatewayId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/definitions/$definitionId': {
      id: '/_authenticated/organizations/$orgId/definitions/$definitionId'
      path: '/definitions/$definitionId'
      fullPath: '/organizations/$orgId/definitions/$definitionId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/workspaces/$workspaceId/end-devices': {
      id: '/_authenticated/organizations/$orgId/workspaces/$workspaceId/end-devices'
      path: '/end-devices'
      fullPath: '/organizations/$orgId/workspaces/$workspaceId/end-devices'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/gateways/$gatewayId/overview': {
      id: '/_authenticated/organizations/$orgId/gateways/$gatewayId/overview'
      path: '/overview'
      fullPath: '/organizations/$orgId/gateways/$gatewayId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute
    }
    '/_authenticated/organizations/$orgId/definitions/$definitionId/overview': {
      id: '/_authenticated/organizations/$orgId/definitions/$definitionId/overview'
      path: '/overview'
      fullPath: '/organizations/$orgId/definitions/$definitionId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute
    }
  }
}

interface AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteChildren {
  AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute
}

const AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteChildren: AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute:
      AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdOverviewRoute,
  }

const AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteChildren {
  AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute
}

const AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteChildren: AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute:
      AuthenticatedOrganizationsOrgIdGatewaysGatewayIdOverviewRoute,
  }

const AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteChildren {
  AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute
}

const AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteChildren: AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute:
      AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdEndDevicesRoute,
  }

const AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsOrgIdRouteRouteChildren {
  AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren
  AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren
  AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren
  AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute: typeof AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute
  AuthenticatedOrganizationsOrgIdGatewaysIndexRoute: typeof AuthenticatedOrganizationsOrgIdGatewaysIndexRoute
  AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute: typeof AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute
}

const AuthenticatedOrganizationsOrgIdRouteRouteChildren: AuthenticatedOrganizationsOrgIdRouteRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRoute:
      AuthenticatedOrganizationsOrgIdDefinitionsDefinitionIdRouteRouteWithChildren,
    AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRoute:
      AuthenticatedOrganizationsOrgIdGatewaysGatewayIdRouteRouteWithChildren,
    AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRoute:
      AuthenticatedOrganizationsOrgIdWorkspacesWorkspaceIdRouteRouteWithChildren,
    AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute:
      AuthenticatedOrganizationsOrgIdDefinitionsIndexRoute,
    AuthenticatedOrganizationsOrgIdGatewaysIndexRoute:
      AuthenticatedOrganizationsOrgIdGatewaysIndexRoute,
    AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute:
      AuthenticatedOrganizationsOrgIdWorkspacesIndexRoute,
  }

const AuthenticatedOrganizationsOrgIdRouteRouteWithChildren =
  AuthenticatedOrganizationsOrgIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationsOrgIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationsRouteChildren {
  AuthenticatedOrganizationsOrgIdRouteRoute: typeof AuthenticatedOrganizationsOrgIdRouteRouteWithChildren
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
}

const AuthenticatedOrganizationsRouteChildren: AuthenticatedOrganizationsRouteChildren =
  {
    AuthenticatedOrganizationsOrgIdRouteRoute:
      AuthenticatedOrganizationsOrgIdRouteRouteWithChildren,
    AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  }

const AuthenticatedOrganizationsRouteWithChildren =
  AuthenticatedOrganizationsRoute._addFileChildren(
    AuthenticatedOrganizationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
